config/routes.rb
Rails.application.routes.draw do

  resources :procedures, :path => 'intervenciones' do 
    collection do 
      get :list, :path => 'todas'
    end
  end

  resources :categories
  devise_for :users, path: "", :path_names => {:sign_up=> 'registrar',:sign_in => 'ingresar', :sign_out => 'salir', :edit=>'editar',:new=>'nueva',:password=>'contraseña'}

  resources :patients, :path => "expedientes", :path_names=>{:edit=> 'editar', :new=>'nuevo'}
  resources :appointments, :path => "citas", :path_names=>{:edit=> 'editar', :new=>'nuevo'} do
    resources :procedures, :path => "intervenciones", :path_names=>{:edit=> 'editar', :new=>'nuevo'}
  end

   root 'welcome#index'

end

app/views/partials/_navigation.html.erb
	<header>
		<nav class="header-green white large-padding">
			<ul class="row center-xs middle-xs">
				<li class="col-md">
					<h1 class="no-margin" id="logo">
						<%= link_to "Consultorio", root_path, class:"title-font"%>
					</h1>
				</li>
				<div class="dropdown col-md">
				  <a class="link-color" id="dLabel" data-target="#" href="/expedientes" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				    Expedientes
				    <span class="caret"></span>
				  </a>
				  <ul class="dropdown-menu" aria-labelledby="dLabel">
				  	<li>
						<%= link_to "Todos", "/expedientes"%>	  		
				  	</li>
				  	<li>
					  	<%= link_to 'Nuevo Paciente', new_patient_path%>
				  	</li>
				  </ul>
				</div>
				<li>					
				<div class="dropdown col-md">
				  <a id="dLabel" data-target="#" href="/citas" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				    Citas
				    <span class="caret"></span>
				  </a>

				  <ul class="dropdown-menu" aria-labelledby="dLabel">
				  	<li>
						<%= link_to "Todas", "/citas"%>
				  	</li>
				  	<li>
					  	<%= link_to 'Nueva Cita', new_appointment_path%>
				  	</li>
				  </ul>
				</div>
				<li class="col-md">
					<%= link_to "Historial Odontologico", "/intervenciones/todas"%>
				</li>
				<% if user_signed_in?%>
					<li class="col-md">
						<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%>
					</li>
					<%else%>
					<li class="col-md">
						<%= link_to "Iniciar sesión", new_user_session_path%>
					</li>
					<%if false%>
					<li class="col-md">
						<%= link_to "Crear cuenta", new_user_registration_path%>
					</li>
					<%end%>
					<%end%>
			</ul>
		</nav>
	</header>