config/routes.rb
Rails.application.routes.draw do

  resources :procedures, :path => 'intervenciones' do 
    collection do 
      get :list, :path => 'todas'
    end
  end

  resources :categories
  devise_for :users, path: "", :path_names => {:sign_up=> 'registrar',:sign_in => 'ingresar', :sign_out => 'salir', :edit=>'editar',:new=>'nueva',:password=>'contraseña'}

  resources :patients, :path => "expedientes", :path_names=>{:edit=> 'editar', :new=>'nuevo'}
  resources :appointments, :path => "citas", :path_names=>{:edit=> 'editar', :new=>'nuevo'} do
    resources :procedures, :path => "intervenciones", :path_names=>{:edit=> 'editar', :new=>'nuevo'}
  end

   root 'welcome#index'

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
	
	validates :descripcion, presence: true, length: { minimum: 15, message: "es muy corto, minimo deben ser 15 caracteres"}
	validates :precio, presence: true

	ATTR_NAMES = {:descripcion => "El campo descripción", :precio=> "El campo precio"}
	  def self.human_attribute_name(attr, options={})
     ATTR_NAMES[attr.to_sym] || super
	  end

	belongs_to :appointment

	def precio_pesos
		"$ #{self.precio}"
	end

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]
  before_action :set_appointment, only: [:show,:edit,:new,:create,:update,:destroy]
  before_action :authenticate_user!
  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.where(appointment_id: params[:appointment_id])
    @appointment=Appointment.find(params[:appointment_id])
  end

  def list
    @procedures=Procedure.all
    @appointments=Appointment.all
  end
  # GET /procedures/1
  # GET /procedures/1.json
  def show
    @appointment=Appointment.find(params[:appointment_id])
  end

  # GET /procedures/new
  def new
    @appointment=Appointment.find(params[:appointment_id])
    @procedure = Procedure.new
  end

  # GET /procedures/1/edit
  def edit
    @appointment=Appointment.find(params[:appointment_id])
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @appointment=Appointment.find(params[:appointment_id])
    @procedure = Procedure.new(procedure_params)
    @procedure.appointment=@appointment
    respond_to do |format|
      if @procedure.save
        format.html { redirect_to appointment_procedure_path(@appointment,@procedure), notice: 'El procedimiento fue creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    @appointment=Appointment.find(params[:appointment_id])
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to appointment_procedure_path(@appointment,@procedure), notice: 'El procedimiento fue acualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    @procedure.destroy
    respond_to do |format|
      format.html { redirect_to appointment_procedures_path(@appointment,@procedure), notice: 'El procedimiento fue eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment=Appointment.find(params[:appointment_id])      
    end
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:nombre, :tipo, :descripcion, :precio,:appointment_id)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<div class="center-xs" style="width:80%; margin:0 auto;">
  <h1><%=procedimiento%> Procedimiento</h1>
  <%= form_for([@appointment,@procedure]) do |f| %>

    <div class="center-xs" style="width:100%; margin:0 auto;">
      <% if @procedure.errors.any? %>
            <div id="error_explanation">
              <%if @procedure.errors.count>1%>
                  <h2><%= pluralize(@procedure.errors.count, "errores") %> evitaron que este procedimiento se guardara:</h2>
              <%else%>
                  <h2><%= pluralize(@procedure.errors.count, "error") %> evitó que este procedimiento se guardara:</h2>
               <%end%>
              <ul>
              <% @procedure.errors.full_messages.each do |message| %>
                  <div class="be-red white top-space btn">
                     <%= message%>
                  </div>
                <%end%>
              </ul>
            </div>
      <% end %>
      </div>

    
    <div class="field">
      <%=f.label :nombre, "Paciente"%>
    </div>
    <div class="field relative">
        <%=@appointment.patient.nombre_completo%>
    </div>
    <div class="field">
      <%=f.label :tipo, "Procedimiento"%>
    </div>
    <div class="field">
      <%= f.collection_select(:tipo, Category.all.order(:nombre), :nombre, :nombre, {:selected => (@procedure.tipo)}) %>
    </div>
    <div class="field">
      <%= f.text_area :descripcion, placeholder:"Descripcion del procedimiento", class:"form-control", style:"height:200px;" %>
    </div>
    <div class="field">
      <%= f.number_field :precio, placeholder:"Precio", :step => 'any'%>
    </div>
    <div class="field">
      <%= f.button "Generar", class:"btn green white" %> |
       <%= link_to 'Regresar', appointment_procedures_path, class:"btn orange white" %>
    </div>
  <% end %>
</div>

app/views/procedures/_listform.html.erb
<% @procedures.each do |procedure|%>
    <%if procedure.tipo==tipo%>
	       <ul class="list-group">
    		    <li class="list-group-item row">
			        <%=link_to procedure.appointment.id, appointment_path(procedure.appointment.id), class:"#{color} btn margin-right" %>
			        <%=procedure.precio_pesos%><%=label_tag "", nil, class:"margin-right" %>
				    <%= procedure.appointment.fecha.strftime("%d-%m-%Y %I:%M %p")%><%=label_tag "", nil, class:"margin-right" %>
			        <%=link_to "Ver completo", appointment_procedure_path(procedure.appointment.id,procedure), class:"green2 white btn" %>
	       		</li>
	      </ul>
    <%end%>
<%end%>

app/views/procedures/edit.html.erb
<div style="width:50%; margin:0 auto;">

	<%= render 'form', procedimiento: "Editar" %>

</div>

app/views/procedures/index.html.erb
<%if false%>
<p id="notice"><%= notice %></p>
<%end%>

<div class="center-xs" style="width:50%; margin:0 auto;">


  <h1>Procedimientos realizados en la cita</h1>

		<ul class="list-group">
	    		    <li class="list-group-item row">
			        <strong class="margin-custom-text-left"></strong> <%=label_tag "", nil, class:"margin-right"%>
				    <%=label_tag "Precio", nil, class:"margin-right-titles" %>
					<%=label_tag "Tipo", nil %>
		        </li>
   </ul>

    <% @procedures.each do |procedure| %>
       <ul class="list-group">
        <li class="list-group-item row">
        <%=link_to "Ver completo", appointment_procedure_path(procedure.appointment.id,procedure), class:"green2 white btn margin-right-index"%>
        <%= procedure.precio_pesos%><%= label_tag "", nil, class:"margin-right-index"%>
        <%= label_tag "", nil%><%= procedure.tipo%>

         </li>
      </ul>
    <% end %>
    <%= link_to 'Volver', appointment_path(@appointment.id), class:"orange white btn margin-left-big" %>
</div>

app/views/procedures/list.html.erb
<div class="center-xs" style="width:95%; margin:0 auto;">

	<form id="live-search" action="" class="styled" method="post">
		    <fieldset>
		        <input type="text" class="text-input" id="filter-procedimientos" value="" placeholder="Buscar" />
		        <span id="filter-count-procedimientos"></span>
		    </fieldset>
		</form>
	<h1>Procedimientos realizados (general)</h1>

	<div class="procedurelist">
	  <ul class="nav nav-tabs" role="tablist">
	    <li  role="presentation" class="active"><a class="gray" href="#general" aria-controls="general" role="tab" data-toggle="tab">General</a></li>
	    <li role="presentation"><a class="color1" href="#limpieza-bucal" aria-controls="limpieza-bucal" role="tab" data-toggle="tab">Limpieza Bucal</a></li>
	    <li role="presentation"><a class="color2" href="#obturacion-empaste" aria-controls="obturacion-empaste" role="tab" data-toggle="tab">Obturacion (Empaste)</a></li>
	    <li role="presentation"><a class="color3" href="#endodoncia" aria-controls="endodoncia" role="tab" data-toggle="tab">Endodoncia</a></li>
	    <li role="presentation"><a class="color4" href="#protesis" aria-controls="protesis" role="tab" data-toggle="tab">Prótesis</a></li>
	    <li role="presentation"><a class="color5" href="#implante-dental" aria-controls="implante-dental" role="tab" data-toggle="tab">Implantes Dentales</a></li>
	    <li role="presentation"><a class="color6" href="#ortodoncia" aria-controls="ortodoncia" role="tab" data-toggle="tab">Ortodoncia</a></li>
	    <li role="presentation"><a class="color7" href="#cosmetica-dental" aria-controls="cosmetica-dental" role="tab" data-toggle="tab">Cosmetica Dental</a></li>
	    <li role="presentation"><a class="color8" href="#cirugia" aria-controls="cirugia" role="tab" data-toggle="tab">Cirugias</a></li>
	  </ul>
	</div>

	<div class="center-xs" style="width:90%; margin:0 auto;">
		<ul class="list-group">
	    		    <li class="list-group-item row">
			        <strong class="margin-custom-text-left">Cita</strong> <%=label_tag "", nil, class:"margin-right-titles"%>
				    <%=label_tag "Precio", nil, class:"margin-right" %>
					<strong class="margin-custom-text-left"></strong><%=label_tag "Fecha", nil, class:"margin-right" %>
		        </li>
	      </ul>
	<div class="tab-content">
	    <div role="tabpanel" class="tab-pane active" id="general">
	    	<% @procedures.each do |procedure|%>
				<ul class="list-group">
				    <li class="list-group-item row">
				    	<%if procedure.tipo=="Limpieza Bucal"%>
				    		<% color= "color1"%>
				    	<%elsif procedure.tipo=="Obturacion (Empaste)"%>
				    		<% color= "color2"%>
				    	<%elsif procedure.tipo=="Endodoncia"%>
				    		<% color= "color3"%>
				    	<%elsif procedure.tipo=="Prótesis"%>
			    			<% color= "color4"%>
				    	<%elsif procedure.tipo=="Implante Dental"%>
							<% color= "color5"%>
				    	<%elsif procedure.tipo=="Ortodoncia"%>
							<% color= "color6"%>
				    	<%elsif procedure.tipo=="Cósmetica Dental"%>
							<% color= "color7"%>
				    	<%elsif procedure.tipo=="Cirugia"%>
				    		<% color= "color8"%>
				    	<%end%>
				        <%=link_to procedure.appointment.id, appointment_path(procedure.appointment.id), class:"#{color} btn margin-right" %>
				        <%=procedure.precio_pesos%><%=label_tag "", nil, class:"margin-right" %>
					    <%= procedure.appointment.fecha.strftime("%d-%m-%Y %I:%M %p")%><%=label_tag "", nil, class:"margin-right" %>
				        <%=link_to "Ver completo", appointment_procedure_path(procedure.appointment.id,procedure), class:"green2 white btn" %>
						</li>
				</ul>
			<%end%>
	    </div>

	    <div role="tabpanel" class="tab-pane" id="limpieza-bucal">
	       	<%= render "listform", tipo: "Limpieza Bucal", color: "color1"%>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="obturacion-empaste">
	     	           	<%= render "listform", tipo: "Obturacion (Empaste)", color: "color2"%>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="endodoncia">
	           	<%= render "listform", tipo: "Endodoncia", color: "color3"%>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="protesis">
	           	<%= render "listform", tipo: "Prótesis", color: "color4"%>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="implante-dental">
	       	<%= render "listform", tipo: "Implante Dental", color: "color5"%>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="ortodoncia">
	  		<%= render "listform", tipo: "Ortodoncia", color: "color6"%>
		</div>
	    <div role="tabpanel" class="tab-pane" id="cosmetica-dental">
	           	<%= render "listform", tipo: "Cósmetica Dental", color: "color7"%>
	    </div>
	    <div role="tabpanel" class="tab-pane" id="cirugia">
	           	<%= render "listform", tipo: "Cirugia", color: "color8"%>
	    </div>
	 </div>    
</div>

app/views/procedures/new.html.erb
<div style="width:50%; margin:0 auto;">
	<%= render 'form', procedimiento: "Nuevo" %>
</div>

app/views/procedures/show.html.erb
<div id="wrapper2" class="center-xs" style="width:40%; margin:0 auto;">

    <h2>REGISTRO DEL PROCEDIMIENTO</h2>
    <p class="top-space"></p>
    <%= form_for(@procedure) do |f|%>
    
      <div class="top-space" style="width:95%;">
        <h4 >
        <%= f.label "Paciente:"%>
        <%=@appointment.patient.nombre_completo%>            
        </h4>
      </div>

      <div class="top-space" style="width:95%;">
        <%= f.label "Tipo de Procedimiento:"%>        
        <%=@procedure.tipo%>
      </div>

      <div class="field">
        <h4 class="large-padding">
        <%= f.label "Descripcion:"%>
        </h4>
        <%=f.text_area :descripcion, :readonly => f.object.persisted?, class:"form-control", style:"height:200px;" %>
      </div>

      <div class="top-space" style="width:95%;">
        <%= f.label "Precio:"%>
      <%=@procedure.precio_pesos%>          
      </div>
      <p>
    <%end%>

  <%= link_to "Editar", edit_appointment_procedure_path(@appointment,@procedure), class:"green cream btn "%> |
  <%= link_to 'Volver', appointment_procedures_path, class:"orange cream btn margin-right" %>
  <%= link_to 'Eliminar', [@appointment,@procedure], method: :delete, data: { confirm: '¿Está seguro?' },class:"be-red cream btn " %>
</div>