config/routes.rb
Rails.application.routes.draw do

  resources :procedures, :path => 'intervenciones' do 
    collection do 
      get :list, :path => 'todas'
    end
  end

  resources :categories
  devise_for :users, path: "", :path_names => {:sign_up=> 'registrar',:sign_in => 'ingresar', :sign_out => 'salir', :edit=>'editar',:new=>'nueva',:password=>'contraseña'}

  resources :patients, :path => "expedientes", :path_names=>{:edit=> 'editar', :new=>'nuevo'}
  resources :appointments, :path => "citas", :path_names=>{:edit=> 'editar', :new=>'nuevo'} do
    resources :procedures, :path => "intervenciones", :path_names=>{:edit=> 'editar', :new=>'nuevo'}
  end

   root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	validates :patient_id, presence: true
	validates :patient_nombre, presence: true
	validates_datetime :fecha, :after => :now
	validates :motivo, presence: true


	ATTR_NAMES = {:patient_id => "El ID", :patient_nombre=> "El campo paciente",:fecha=>""}
	  def self.human_attribute_name(attr, options={})
     ATTR_NAMES[attr.to_sym] || super
	  end


	belongs_to :patient

	has_many :procedures, :dependent => :destroy

	def patient_nombre
		patient.try(:nombre_completo)
	end

	def patient_nombre=(nombre)
		self.patient=Patient.find_or_create_by_nombre(nombre) if nombre.present?
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @procedures=Procedure.where(appointment_id: params[:id])
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @procedure=Procedure.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
   @appointment = Appointment.new(appointment_params)
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: '¡Creado!' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: '¡Actualizado!' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Cita eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:motivo, :fecha, :anotaciones, :user_id,:patient_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<div class="center-xs" style="width:80%; margin:0 auto;">
  <%= form_for(@appointment) do |f| %>
    <% if @appointment.errors.any? %>
      <div id="error_explanation">
      <%if @appointment.errors.count>1%>
        <h2><%= pluralize(@appointment.errors.count, "errores") %> evitaron que esta cita se guardara:</h2>
      <%else%>
        <h2><%= pluralize(@appointment.errors.count, "error") %> evitó que esta cita se guardara:</h2>
       <%end%>

        <ul>
        <% @appointment.errors.full_messages.each do |message| %>
          <div class="btn be-red top-space white"><%= message %></div>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :patient_nombre, placeholder: "Paciente", data: {autocomplete_source: Patient.order(:nombre).map{ |t| { :label => t.nombre_busqueda, :value => t.id }}}, class:"form-control-citas"%>
      <%= f.hidden_field :patient_id, id: 'patient_id' %>
    </div>
    <div class="field relative">
      <%= f.text_field :fecha, placeholder:"Fecha", class:"form-control-citas" %>
    </div>
    <div class="field">
        <%= f.label :motivo, "Motivo"%>
          <%= f.select(:motivo, [['Revisión',"Revisión"],['Intervención Programada','Intervención Programada']], {:selected => (@appointment.motivo?)}) %>
    </div>
    <div class="field">
      <%= f.text_area :anotaciones, placeholder:"Anotaciones previas", class:"form-control", style:"height:200px;" %>
    </div>
    <div class="actions">
      <%= f.submit "Guardar", class:"btn green white margin-right" %>
      <%= link_to 'Atras', @appointment, class:"btn orange white" %>
    </div>
  <% end %>
  <p></p>
</div>
  <div class="panel-group center-xs" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Mostrar/Ocultar Agenda
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
          <div id="calendarCita" style="background-color:"#FFFFFF";">
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/appointments/edit.html.erb
<div style="width:50%; margin:0 auto;">
	<h1>Editar Cita</h1>
	<%= render 'form', mostrar: "Mostrar" %>
</div>

app/views/appointments/index.html.erb
<div class="row center-xs">
  <div class="col-xs-7 com-md-6">
      <h1>Citas</h1>
      <div id="calendar" style="background-color:#FFFFFF;">
      </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div style="width:50%; margin:0 auto;">
	<h1>Nueva Cita</h1>
	<%= render 'form' %>
</div>

app/views/appointments/show.html.erb
<div style="width:40%; margin:0 auto;">

  <%= form_for(@appointment) do |f|%>
    <div class="field row">
      <h4 class="large-padding">
      <%= f.label "Paciente:"%>
      </h4>   
      <h4 class="padding-campos dato-form-controll"> 
      <%=@appointment.patient.nombre_completo%>  
      </h4>
    </div>
    <div class="field row">
      <h4 class="large-padding">
      <%= f.label "Fecha agendada:"%>
      </h4>   
      <h4 class="padding-campos dato-form-controll"> 
      <%=@appointment.fecha.strftime("%d-%m-%Y %I:%M %p")%>
      </h4>
    </div>
    <div class="field row">
      <h4 class="large-padding">
      <%= f.label "Motivo de la cita:"%>
      </h4>   
      <h4 class="padding-campos dato-form-controll"> 
      <%=@appointment.motivo%>          
      </h4>
    </div>
    <div class="field row">
      <h4 class="large-padding">
      <%= f.label "Anotaciones:"%>
      </h4>   
      <%=f.text_area :anotaciones, :readonly => f.object.persisted?, class:"form-control", style:"height:200px;" %>
    </div>
    <%if false%>
        <div class="field row">
          <h4 class="large-padding">
          <%= f.label "Dentista:"%>
          </h4>   
          <h4 class="padding-campos dato-form-controll"> 
          <%=@appointment.user.username%> 
          </h4>
        </div>
    <%end%>
    <p>
  <%end%>

  <%= link_to "Editar", edit_appointment_path(@appointment), class:"green cream btn "%> |
  <%= link_to 'Volver', appointments_path, class:"orange cream btn margin-right" %>
  <%= link_to 'Eliminar', @appointment, method: :delete, data: { confirm: '¿Está seguro?' },class:"be-red cream btn " %>
</div>


<div class="center-xs" style="width:55%; margin:0 auto;">

  <div class="field center-xs">
    <strong>Formulario de intervención</strong><p></p>
    <%= link_to 'Generar', new_appointment_procedure_path(@appointment,@procedure), class:"blue cream btn" %>
  </div>
  <div class="panel-group center-xs top-space" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Clic para mostrar/ocultar procedimientos realizados en la cita
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <ul class="list-group">
              <li class="list-group-item row">
              <%= label_tag "", nil, class:"margin-right"%>
              <%=label_tag "Precio", nil, class:"margin-right-titles", style:"margin-left:30px;"%>
              <%=label_tag "Tipo", nil%>
            </li>
        </ul>
              <% @procedures.each do |procedure| %>
                 <ul class="list-group">
                  <li class="list-group-item row">
                   <%=link_to "Ver completo", appointment_procedure_path(procedure.appointment.id,procedure), class:"green2 white btn margin-right-index", style:"margin-left:10px;"%>
                    <%= procedure.precio_pesos%><%= label_tag "", nil, class:"margin-right-index"%>
                    <%= procedure.tipo%>
                   </li>
                </ul>
              <% end %>
        </div>
      </div>
    </div>
  <%= link_to 'Ver Todos', appointment_procedures_path(@appointment,@procedure), class:"green2 white btn top-space" %>
</div>